//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FedyaZachet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public int Amount { get; set; }
        public decimal Price { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Category Category1 { get; set; }
    }
}
